# Generated by Django 2.1.5 on 2019-03-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmgQuotesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite', models.CharField(max_length=200, verbose_name='Composición')),
                ('smg01', models.FloatField(verbose_name='SMG01')),
                ('smg02', models.FloatField(verbose_name='SMG02')),
                ('smg10', models.FloatField(verbose_name='SMG10')),
                ('smg20', models.FloatField(verbose_name='SMG20')),
                ('smg30', models.FloatField(verbose_name='SMG30')),
                ('smg40', models.FloatField(verbose_name='SMG40')),
                ('smg50', models.FloatField(verbose_name='SMG50')),
                ('smg60', models.FloatField(verbose_name='SMG60')),
                ('smg70', models.FloatField(verbose_name='SMG70')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Valor',
                'ordering': ['created'],
            },
        ),
    ]
