# Generated by Django 2.1.5 on 2019-04-03 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Nombre')),
                ('phone', models.TextField(max_length=20, verbose_name='Teléfono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asesor Comercial',
                'verbose_name_plural': 'Asesores Comerciales',
                'ordering': ['created'],
            },
        ),
        migrations.AlterModelOptions(
            name='smgquotestable',
            options={'ordering': ['created'], 'verbose_name': 'Valor', 'verbose_name_plural': 'Valores'},
        ),
    ]
