# Generated by Django 2.1.5 on 2019-03-27 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190327_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='projects', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
